[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django==5.1.1",
    "django-cors-headers==4.6.0",
    "djangorestframework==3.15.2",
    "psycopg2-binary>=2.9.12",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "flake8-isort>=7.0.0",
]
